---

- name: BIG-IP Automation
  hosts: 192.168.152.140

  tasks:
  - name: Create pool
    bigip_pool:
        server: 192.168.152.140
        user: "admin"
        password: "admin"
        pool: "teste_ansible_playbook"
        state: "present"
        monitor_type: "and_list"
        monitors:
           - "gateway_icmp"
        lb_method: "ratio-member"
        validate_certs: "false" 
    delegate_to: localhost

  - name: Add PoolMembers
    bigip_pool_member:
        server: "192.168.152.140"
        user: "admin"
        password: "admin"
        state: "present"
        host: "{{ item.host }}"
        pool: "teste_ansible_playbook"
        port: 0
        validate_certs: "false"
    with_items: 
        - host: "10.1.3.47"
        - host: "10.1.2.65"
        - host: "10.0.0.22"
    delegate_to: localhost


  - name: Create VirtualServer
    bigip_virtual_server:
        server: "192.168.152.140"
        user: "admin"
        password: "admin"
        state: "present"
        partition: "Common"
        name: "vs_teste_ansible"
        destination: 192.168.1.14
        port: 0
        pool: "teste_ansible_playbook"
        snat: "Automap"
        description: "Test Virtual Server - Ansible" 
        all_profiles:
            - "fastL4"
        validate_certs: "false"
    delegate_to: localhost                     


  - name: Save the Running Configuration of the BIG-IP
    bigip_config:
        save: yes
        server: "192.168.152.140"
        user: "admin"
        password: "admin"
        validate_certs: "false"
    delegate_to: localhost   
