---

- name: Habilitando PoolMember
  hosts: bigip
  
  tasks:
  - name: PoolMember Online"
    bigip_pool_member:
        server: "192.168.152.140"
        user: "admin"
        password: "admin"
        state: "present"
        session_state: "enabled"
        monitor_state: "enabled"
        pool: "teste_ansible_playbook"
        host: 10.1.3.47
        port: 0
        validate_certs: "false"
    delegate_to: localhost

  - name: Save the Running Configuration of the BIG-IP
    bigip_config:
        save: yes
        server: "192.168.152.140"
        user: "admin"
        password: "admin"
        validate_certs: "false"
    delegate_to: localhost
