---

- name: Colocando Pool Member Offline/Online
  hosts: bigip

  vars:
     ipbigip: 10.1.2.128
     userbigip: "admin"
     passuser: "admin"
     poolname: "teste_ansible_playbook"
     poolmember: 10.1.3.47
     portpoolmember: 0
          
  
  tasks:
  - name: PoolMember Forced Offline
    bigip_pool_member:
        server: "{{ ipbigip }}"
        user: "{{ userbigip }}"
        password: "{{ passuser }}"
        state: "present"
        session_state: "disabled"
        monitor_state: "disabled"
        pool: "{{ poolname }}"
        host: "{{ poolmember }}"
        port: "{{ portpoolmember }}"
        validate_certs: "false"
    delegate_to: localhost
    tags: 
       - offline-pool-member
 
  - name: PoolMember Online
    bigip_pool_member:
        server: "{{ ipbigip }}"
        user: "{{ userbigip }}"
        password: "{{ passuser }}"
        state: "present"
        session_state: "enabled"
        monitor_state: "enabled"
        pool: "{{ poolname }}"
        host: "{{ poolmember }}"
        port: "{{ portpoolmember }}"
        validate_certs: "false"
    delegate_to: localhost
    tags: 
       - online-pool-member    

  - name: Sync configuration from device to group
    bigip_configsync_actions:
        device_group: "sync-failover"
        sync_device_to_group: yes
        server: "{{ ipbigip }}"
        user: "{{ userbigip }}"
        password: "{{ passuser }}"
        validate_certs: "false"
    delegate_to: localhost
    tags:
       - sync-to-group

  - name: Save the Running Configuration of the BIG-IP
    bigip_config:
        save: yes
        server: "{{ ipbigip }}"
        user: "{{ userbigip }}"
        password: "{{ passuser }}"
        validate_certs: "false"
    delegate_to: localhost
    tags:
       - save-config-bigip     
