---

- name: Colocando Pool Member Offline/Online
  hosts: bigip
  
  tasks:
  - name: PoolMember Forced Offline"
    bigip_pool_member:
        server: "192.168.152.140"
        user: "admin"
        password: "admin"
        state: "present"
        session_state: "disabled"
        monitor_state: "disabled"
        pool: "teste_ansible_playbook"
        host: 10.1.3.47
        port: 0
        validate_certs: "false"
    delegate_to: localhost
    tags: 
       - offline-pool-member
 
  - name: PoolMember Online
    bigip_pool_member:
        server: "192.168.152.140"
        user: "admin"
        password: "admin"
        state: "present"
        session_state: "enabled"
        monitor_state: "enabled"
        pool: "teste_ansible_playbook"
        host: 10.1.3.47
        port: 0
        validate_certs: "false"
    delegate_to: localhost
    tags: 
       - online-pool-member    

  - name: Sync configuration from device to group
    bigip_configsync_actions:
        device_group: "sync-failover"
        sync_device_to_group: yes
        server: "192.168.152.140"
        user: "admin"
        password: "admin        "
        validate_certs: "false"
    delegate_to: localhost
    tags: 
       - sync-to-group

  - name: Save the Running Configuration of the BIG-IP
    bigip_config:
        save: yes
        server: "192.168.152.140"
        user: "admin"
        password: "admin"
        validate_certs: "false"
    delegate_to: localhost
    tags:
       - save-config-bigip     
